name: Commit Changes to Dev Branch

on:
  push:
    branches:
      - stable

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Commit changes to Dev branch
      run: |
        git checkout dev
        git merge --ff-only stable
        git push origin dev
